name: Hello World Workflow
run-name: Hello World Run Name
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "ECHO"
      run: echo "SHA ${{ github.sha }} BRANCH ${{ github.ref_name }} REPO ${{ github.repository }}"
    - name: Fetch Repository Languages
      run: |
        curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        https://api.github.com/repos/${{ github.repository }}/languages | jq