name: Hello World Workflow
run-name: Hello World Run Name
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "ECHO"
      run: echo "SHA ${{ github.sha }}\nBRANCH ${{ github.ref_name }}\nREPO ${{ github.repository }}"